instance of DSC_TimeZone as $DSC_TimeZone1ref
{
ModuleName = "ComputerManagementDsc";
IsSingleInstance = "Yes";
ResourceID = "[TimeZone]TimeZoneExample";
SourceInfo = "::7::9::TimeZone";
TimeZone = "Tonga Standard Time";
ModuleVersion = "8.2.0";
ConfigurationName = "DSCConfig";
};

instance of OMI_ConfigurationDocument
{
Version="2.0.0";
MinimumCompatibleVersion = "1.0.0";
CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
Name="DSCConfig";
};
