[ClassVersion("1.0.0.0")]
class Reason
{
    [Read] String Code;
    [Read] String Phrase;
};

[ClassVersion("1.0.0.0"), FriendlyName("PesterResource")]
class MSFT_PesterResource : OMI_BaseResource
{
    [Key, Description("Specifies the name of the Pester script included in the module")] String PesterFileName;
    [Read] String Status;
    [Read, EmbeddedInstance("Reason")] String Reasons[];
};