instance of OMI_ConfigurationDocument
{
    Version = "1.0.0";
    MinimumCompatibleVersion = "1.0.0";
    CompatibleVersionAdditionalProperties = {"Omi_BaseResource:ConfigurationName"};
    Name = "CustomConfig";
};
