pr:
  autoCancel: 'true'
  branches:
    include:
      - feature/*
      - f/*
      - bug/*
      - b/*
      - chore/*
      - c/*
  paths:
    exclude:
        - /bin/*
        - /tools/azure-pipelines-pr.yml
        - /tools/azure-pipelines-release.yml
        - README.md
        - CODE_OF_CONDUCT.md
        - SECURITY.md
        - LICENSE
        - changelog.md
        - .gitignore
        - .github/*

jobs:
  - job: Test
    strategy:
      matrix:
        # Blocking issue in 18.04
        # running cmdlets from Ubuntu 18.04:
        #  imageName: ubuntu-18.04
        running cmdlets from Ubuntu 16.04:
          imageName: ubuntu-16.04
        # Blocking issue in MacOS on ADO
        # libmi library not available
        # will be fixed with new DSC
        # running cmdlets from macOS Mojave:
        #   imageName: macOS-10.14
        # running cmdlets from macOS Catalina:
        #   imageName: macOS-10.15
        running cmdlets from Windows 2019:
          imageName: windows-2019
        running cmdlets from Windows 2016:
          imageName: vs2017-win2016
    pool:
      vmImage: $(imageName)
    steps:
      - task: UniversalPackages@0
        displayName: Download Linux agent
        inputs:
          command: download
          vstsFeed: guestconfiguration
          vstsFeedPackage: linux_agent
          vstsPackageVersion: '*'
          downloadDirectory: '$(Build.SourcesDirectory)/bin/'
      - task: UniversalPackages@0
        displayName: Download Windows agent
        inputs:
          command: download
          vstsFeed: guestconfiguration
          vstsFeedPackage: windows_agent
          vstsPackageVersion: '*'
          downloadDirectory: '$(Build.SourcesDirectory)/bin/'
      - task: PowerShell@2
        displayName: Install modules
        inputs:
          pwsh: 'true'
          targetType: inline
          failOnStderr: true
          script: |
            $modules = (Import-PowerShellDataFile "$env:BUILD_SOURCESDIRECTORY/GuestConfiguration.psd1").RequiredModules
            $modules += 'PSScriptAnalyzer'
            Install-Module -Name $modules -Repository 'PSGallery' -Force -AllowClobber
            Install-Module -Name 'Pester' -RequiredVersion 5.0.4 -AllowClobber -SkipPublisherCheck -Repository 'PSGallery' -Force
      - task: PowerShell@2
        enabled: 'true'
        displayName: Enable Experimental Feature
        inputs:
          pwsh: 'true'
          targetType: inline
          continueOnError: 'true'
          script: |
            if ($IsWindows) {$delimiter = ";"} else {$delimiter = ":"}
            $firstPSModulePathFolder = ($Env:PSModulePath -split $delimiter)[0]
            Copy-Item $env:BUILD_SOURCESDIRECTORY (Join-Path $firstPSModulePathFolder 'GuestConfiguration') -Recurse
            $gcModulePath = Join-Path (Join-Path $firstPSModulePathFolder 'GuestConfiguration') 'GuestConfiguration.psd1'
            Import-Module $gcModulePath -Force
            Enable-ExperimentalFeature -Name GuestConfiguration.Pester
      - task: PowerShell@2
        enabled: 'true'
        displayName: Pester v5 unit tests
        inputs:
          pwsh: 'true'
          targetType: inline
          continueOnError: 'true'
          script: |
            if ($IsWindows) { $env:ADO = $true; Invoke-Pester -CI }
            else { sudo pwsh { $env:ADO = $true; Invoke-Pester -CI }}
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: 'testResults.xml'
        displayName: Publish test result
  - job: PublishArtifactToAzureDevOpsBuild
    dependsOn: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: PowerShell@2
        displayName: Stage module artifact
        inputs:
          pwsh: 'true'
          targetType: inline
          failOnStderr: true
          errorActionPreference: stop
          script: |
            New-Item $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration -type Directory
            Copy-Item -Path $env:BUILD_SOURCESDIRECTORY/DscResources -Destination $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration/DscResources -Recurse
            Remove-Item $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration/DscResources/MSFT_PesterResource/Tests -Force -Recurse
            Copy-Item -Path $env:BUILD_SOURCESDIRECTORY/helpers -Destination $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration/helpers -Recurse
            Copy-Item -Path $env:BUILD_SOURCESDIRECTORY/GuestConfiguration.psd1 -Destination $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration/GuestConfiguration.psd1
            Copy-Item -Path $env:BUILD_SOURCESDIRECTORY/GuestConfiguration.psm1 -Destination $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration/GuestConfiguration.psm1
            Copy-Item -Path $env:BUILD_SOURCESDIRECTORY/LICENSE -Destination $env:BUILD_ARTIFACTSTAGINGDIRECTORY/GuestConfiguration/LICENSE
      - task: UniversalPackages@0
        displayName: Universal download
        inputs:
          command: download
          vstsFeed: guestconfiguration
          vstsFeedPackage: gc_agents
          vstsPackageVersion: '*'
          downloadDirectory: '$(Build.ArtifactStagingDirectory)/GuestConfiguration/bin/'
      - task: PublishPipelineArtifact@1
        displayName: Publish artifact
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/GuestConfiguration'
          artifactName: GuestConfiguration
