trigger: none

variables:
  triggeringPipelineAlias: PublicPipeline
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  testArtifactName: testResults

resources:
  pipelines:
  - pipeline: PublicPipeline # $(triggeringPipelineAlias)
    source: Azure.GuestConfiguration.Public
    trigger:
      branches:
        - master

pool:
  vmImage: 'ubuntu 16.04'

stages:
  - stage: init_private_build
    jobs:
      - job: retrieve_previous_pipeline_artifact
        displayName: 'Downloading Public Pipeline Output'
        timeoutInMinutes: 0
        steps:
          - download: PublicPipeline # $(triggeringPipelineAlias)
            artifact: $(buildFolderName)

          - pwsh: |
              dotnet tool install --global GitVersion.Tool
              $gitVersionObject = dotnet-gitversion | ConvertFrom-Json
              $gitVersionObject.psobject.properties.Foreach{
                  Write-Host -Object "Setting Task Variable '$($_.Name)' with value '$($_.Value)'."
                  Write-Host -Object "##vso[task.setvariable variable=$($_.Name);]$($_.Value)"
              }
              Write-Host -Object "##vso[build.updatebuildnumber]$($gitVersionObject.FullSemVer)"
            displayName: Calculate ModuleVersion (GitVersion)
            name: gitVersion

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Pipeline Artifact'
            inputs:
              targetPath: '$(Pipeline.Workspace)/PublicPipeline/$(buildFolderName)/'
              artifact: $(buildArtifactName)
              publishLocation: 'pipeline'
              parallel: true

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Pipeline Artifact'
            inputs:
              buildType: 'current'
              artifactName: $(buildArtifactName)
              targetPath: '$(Build.SourcesDirectory)/$(buildArtifactName)'

          - task: EsrpCodeSigning@1
            displayName: ESRP CodeSigning
            inputs:
              ConnectedServiceName: e0624a17-df22-45d7-8e38-c9a3bb0dfba5
              FolderPath: '$(Pipeline.Workspace)/PublicPipeline/$(buildFolderName)/'
              Pattern: '*.asc'
              signConfigType: inlineSignParams
              CertificateId: CP-450779-Pgp
              inlineOperation: >-
                [
                  {
                    "KeyCode": "CP-450779-Pgp",
                    "OperationCode": "LinuxSign",
                    "ToolName": "sign",
                    "ToolVersion": "1.0",
                    "Parameters": {}
                  }
                ]
