name: hellopwsh
on: [push]

jobs:

  pwsh:
    runs-on: ubuntu-latest
      
    steps:
      - name: Pester
        run: |
        Install-Module 'Pester' -Force
          Describe 'Something' {
            It 'can be evaluate by GH Actions' {
              $true | Should -Be $true
            }
          }
          Get-Variable
        shell: pwsh