name: hellopwsh
on: [push]

jobs:

  pwsh:
    runs-on: ubuntu-latest
      
    steps:
      - name: Pester
        run: |
          $global:progresspreference = 'SilentlyContinue'
          Install-Module 'Pester' -Force
          $ChangedFiles = git diff-tree --no-commit-id --name-only -r $Env:GITHUB_SHA
          Describe 'Included files' {
            It 'should have one' {
              $ChangedFiles | Should -Be 'hellopwsh.yml'
            }
          }
          git diff-tree --no-commit-id --name-only -r $Env:GITHUB_SHA
        shell: pwsh