name: hellopwsh
on: [push]

jobs:

  pwsh:
    runs-on: ubuntu-latest
      
    steps:
      - run: pwsh -command {write-host "hello, pwsh"}

      - name: Display the path
        run: echo ${env:PATH}
        shell: pwsh