name: hellopwsh
on: [push]

jobs:

  pwsh:
    runs-on: ubuntu-latest
      
    steps:
      - name: Talk to API
        run: |
          Invoke-RestMethod -Method Get -Uri https://api.github.com/user -Headers @{authorization = "Bearer ${{secrets.GITHUB_TOKEN}}";'content-type'='application-json'}
        shell: pwsh