name: hellopwsh
on: [push]

jobs:

  pwsh:
    runs-on: ubuntu-latest
      
    steps:
      - name: Talk to API
        run: |
          $Files = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/$Env:GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/files" -Headers @{authorization = "Bearer ${{secrets.GITHUB_TOKEN}}"} -ContentType 'application/json' 
          $Files | % filename
        shell: pwsh