name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not been updated within 14 days'
        stale-pr-message: 'This PR has not been updated within 14 days'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 14
<<<<<<< HEAD
        days-before-close: 180
=======
        days-before-close: -1
>>>>>>> 6ba8bdd... Label Issues/PRs stale after 14 days (#86)
